### PR TITLE
fix(settings): select proper brain model

### PR DESCRIPTION
**Pull request by B0rrA**
# Description

Fix select brain model on setting, this solve this issues

- https://github.com/StanGirard/quivr/issues/832
When you load settings of a brain, the system load only the "free models" by default, only when the data is retrieved the system load the "paid models". After that there is two problem, the value obtained for the model of the brain select is not passed to the component so it not selected, this will be solved by adding this:

```
if (brain.model !== undefined) {
        setValue("model", brain.model);
      }
```

But other issue appear, the paid models are loaded fully a bit later than the value is passed. This means that if your model use GPT-4, the select component with not be setted to this because there isnt load yet. So i wrapped to wait until the paid model are loaded.

```
setTimeout(() => {
      if (brain.model !== undefined) {
        setValue("model", brain.model);
      }
    },50);
```

- https://github.com/StanGirard/quivr/issues/856
When you change the brain model you need to press enter to save this new value. First i try to call directly to submit the form when the value on the select component is changued.

```
onChange={() => {
            void handleSubmit();
          }}
```

After that the handleSubmit has a validation that the form need to have some value changed before save, but change the value on the select has no effect on the form, so this check fails and the new value is not saved. To solve this, i added a flag to the handleSubmit event to ask if "form is dirty" validation will be checked before save. 

```
const handleSubmit = async (**checkDirty:boolean**) => {
    const hasChanges = Object.keys(dirtyFields).length > 0;

    if (!hasChanges && checkDirty) {
      return;
    }
```

And updated the onChange event of the select component

```
onChange={() => {
            void handleSubmit(false); // Trigger form submission
          }}
```

## Checklist before requesting a review

Please delete options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented hard-to-understand areas
- [x] I have ideally added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

### CODE REVIEW

**Comment by StanGirard** [comment]
@mamadoudicko wdyt ?

**Comment by mamadoudicko** [comment]
Hello @B0rrA,

I'm having some difficulty understanding your PR. The highlighted issues don't appear to be directly related to this. 

Could you please provide a description of what you're attempting to address?

Thank you!

**Comment by B0rrA** [comment]
@mamadoudicko if you know extra clarification or need some change, please let me know

**Comment by mamadoudicko** [comment]
I see now, thanks for the fix @B0rrA!

**Pull request merged**
