### PR TITLE
Adds pytesseract, tesseract and poopler-utils

### PR DESCRIPTION
**Pull request by MeTaNoV**
To enable the ingestion of copy protected PDF via OCR instead of text extraction

# Description

Copy protected PDF can't be properly imported via the standard langchain loader.

See the following errors:

```
2023-11-15 14:16:31,927 [INFO] models.files: Computing documents from file Cradle to Cradle Criteria for the built environmen.pdf
[nltk_data] Downloading package punkt to
[nltk_data]     /home/pascal_gula_luccid_ai/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/pascal_gula_luccid_ai/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
Error processing file: detectron2 is not installed, pytesseract is not installed and the text of the PDF is not extractable. To process this file, install detectron2, install pytesseract, or remove copy protection from the PDF.
```

```
2023-11-15 15:04:14,624 [INFO] models.files: Computing documents from file Cradle to Cradle Criteria for the built environmen.pdf
Error processing file: Unable to get page count. Is poppler installed and in PATH?
```

```
023-11-15 15:59:11,886 [INFO] models.files: Computing documents from file Cradle to Cradle Criteria for the built environmen.pdf
Error processing file: tesseract is not installed or it's not in your PATH. See README file for more information.
```

## Checklist before requesting a review

Please delete options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented hard-to-understand areas
- [x] I have ideally added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

## Screenshots (if appropriate):

None

### CODE REVIEW

**Comment by StanGirard** [comment]
Thanks 🙏 could you tell me the difference in size that it incurs ?

**Comment by MeTaNoV** [comment]
Sure, here you go:

```
Old:
quivr-backend-core   latest    056750d86247   2 minutes ago   13.4GB
New:
quivr-backend-core   latest    742c5d235313   15 hours ago    13.5GB
```

It is already massive and doesn't change much hopefully. I saw you tried some multi-stage build that might bring this size down. I was surprised how fast my volume was filling, now I know exactly why! :)

Tell somewhere in dev dock to `docker images prune` since during dev, you have tons of dangling images lying around! :D

PS: probablement à bientôt à Paris! ;)

**Comment by StanGirard** [comment]
Damn I really need to tackle this issue. It is not possible to continue like that. 

I'll try it on tuesday. On vacation with access to limited internet. 

Thanks a lot and check your mails ;)

**Comment by StanGirard** [comment]
Damn I really need to tackle this issue. It is not possible to continue like that. 

I'll try it on tuesday. On vacation with access to limited internet. 

Thanks a lot and check your mails ;)

**Comment by MeTaNoV** [comment]
@StanGirard looks like a more general problem about the tests! :)

**Comment by StanGirard** [comment]
Yeah they don't run on contributors PR 🗡️

**Comment by MeTaNoV** [comment]
Alright, should I do anything else ? (PR Title?)

**Pull request merged**
