### PR TITLE
improve (importing): reorganization of the import structure

### PR DESCRIPTION
**Pull request by MaHDiaLaGaB**
# Description

This pull request includes a reorganization of the import structure in Python. The changes made involve modifying the imports to start with '**.brain' for example** within the '__init__' file and fixing all the related imports in the 'backend/core' directory.

## Benefits:

- Improved modularity and maintainability of the codebase.
- Enhanced code readability and navigation.
- Prevention of naming conflicts.

## Checklist before requesting a review

Please delete options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ]  I have commented hard-to-understand areas
- [ ] I have ideally added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Review by gozineb — APPROVED** [review]
Thank you for your contribution @MaHDiaLaGaB !  Really appreciate the reorganization 😀

**Review by gozineb — CHANGES_REQUESTED** [review]
Backends tests are failing because of wrong import in some __init__.py . Ping me when this is fixed so that I can approve your awesome PR !

**Comment by MaHDiaLaGaB** [comment]
@gozineb how i can make the **Check PR title conventional commit/lint (pull_request)**  and **Code Review GPT / build (pull_request) pass the CI**
the **Code Review GPT / build (pull_request)** is requesting the `OPENAI_API_KEY` and the check PR title throeing `Resource not accessible by integration`

**Comment by gozineb** [comment]
Hi @MaHDiaLaGaB, as this is a PR from your repository, we wont be able to make these two actions go green (Check PR title conventional commit/lint (pull_request) and Code Review GPT / build (pull_request) pass the CI)
I was referencing the errors in the Backend Tests/build: 
Screenshot 2023-08-17 at 18 40 51

**Comment by MaHDiaLaGaB** [comment]
@gozineb Now the tests are passing locally I hope it will be here.

**Comment by gozineb** [comment]
Seems to be resolved, you just have some conflicts, I can't push on your branch :/

**Comment by MaHDiaLaGaB** [comment]
@gozineb i just resolved the conflict

**Comment by MaHDiaLaGaB** [comment]
@gozineb I think i am good to go now, I fixed all the conflicted files

**Review by gozineb — APPROVED** [review]

**Pull request merged**
