### PR TITLE
feat(translations): implemented internationalization

### PR DESCRIPTION
**Pull request by B0rrA**
# Description

### ¡Hola Quivr! 🌐🥳

Add a feature to translate the GUI and added **Spanish Translations** for the app and leaving posibility to add others. This feature use i18next and the selected language value is saved in localstorage for reload purposes.

Translations are located at **_frontend\public\locale_**

### Set initial and fallback language:

Open **i18next.config** located at **_frontend\lib\config\i18next.config_**

```
i18n.use(backend)
    .use(initReactI18next)
    .init({
        lng: 'en', #InitialLanguage
        loadPath: '/locales/{{lng}}/{{ns}}.json',
        fallbackLng: 'en', #FallbackLanguage
        debug: true
    })
```

The value needs to match the translation folder name.

### To add a new one follow this steps:

1- Duplicate the "en" folder located at _frontend\public\locale_
2- Rename the new folder to match de new language. eg PT (Portuguese)
3- Update new file translations values
4- Add the new language to the dropdown by including it to the component:
_frontend\lib\components\NavBar\components\NavItems\components\LanguageDropDown\hooks\useLanguageHook.ts_

```
const languages = [
      { 
        id: "en",
        name: 'English'
      },
      {
        id: "es",
        name: 'Español'
      },
     //add here
    ];
```

## Checklist before requesting a review

Please delete options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented hard-to-understand areas
- [x] I have ideally added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

## Screenshots (if appropriate):

image

image

### CODE REVIEW

**Comment by StanGirard** [comment]
This is awesome ! I'll check in depth tomorrow morning

**Comment by StanGirard** [comment]
There is an issue with a hook I think.

The page loads the internationalization after it is loader. 


https://github.com/StanGirard/quivr/assets/19614572/9d3791ae-b3b7-4923-9363-29ff7934e243

**Comment by gozineb** [comment]
Awesome PR @B0rrA ! Thanks ! 🏆 
Could you possibly use typescript instead of json in the translations files? Having typed translation objects would avoid any future missing translation paths. Let me know if you're down for that in this PR or we could do it in a next one 🌟

**Comment by gozineb** [comment]
Hello @B0rrA, any updates on this ? Let me know if I can help as we're currently working a lot on the frontend with brains managament so conflicts are going to become trouble, sorry about that !

**Comment by B0rrA** [comment]
@gozineb @StanGirard a think both issues are gone now.

**Comment by StanGirard** [comment]
Thanks a lot that is a huge PR ! 

Unfortunately there are just a few issues. Do a yarn build and you'll see ;) 

Mainly "use client" missing

**Comment by B0rrA** [comment]
> Thanks a lot that is a huge PR !
> 
> Unfortunately there are just a few issues. Do a yarn build and you'll see ;)
> 
> Mainly "use client" missing

Fixed! Sorry about that, there was some of my "over the hour" changes that break the code xD

**Review by mamadoudicko — APPROVED** [review]

**Pull request merged**
